# Generated by Django 3.2.4 on 2021-06-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='artist',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
