# Generated by Django 3.2.4 on 2021-06-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandnetwork', '0002_release_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='cover_image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='artist',
            name='logo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='release',
            name='artwork',
            field=models.CharField(max_length=300),
        ),
    ]
