# Generated by Django 3.2.4 on 2021-06-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20210610_2045'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='users', to='artists.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='musician',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artists.musician'),
        ),
    ]
