# Generated by Django 3.2.4 on 2021-06-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20210611_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='user',
            name='musician',
        ),
    ]
