# Generated by Django 3.2.4 on 2021-06-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('location', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('date_time', models.DateTimeField()),
                ('price', models.CharField(max_length=10)),
                ('artists', models.ManyToManyField(blank=True, related_name='gigs', to='artists.Artist')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='gigs.venue')),
            ],
        ),
    ]
