# Generated by Django 3.2.4 on 2021-07-26 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_initial'),
        ('gigs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_venues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gig',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_gigs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gig',
            name='headliner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_headliner', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='gig',
            name='support_artists',
            field=models.ManyToManyField(blank=True, related_name='gigs', to='artists.Artist'),
        ),
        migrations.AddField(
            model_name='gig',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='gigs.venue'),
        ),
    ]
