# Generated by Django 3.2.4 on 2021-06-11 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_gigs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venue',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_venues', to=settings.AUTH_USER_MODEL),
        ),
    ]
