# Generated by Django 3.2.4 on 2021-06-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20210611_1237'),
        ('gigs', '0002_auto_20210611_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='artists',
        ),
        migrations.AddField(
            model_name='gig',
            name='headliner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='headliner', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='gig',
            name='support_artists',
            field=models.ManyToManyField(blank=True, related_name='support_artists', to='artists.Artist'),
        ),
    ]
