# Generated by Django 3.2.4 on 2021-06-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20210611_1237'),
        ('gigs', '0003_auto_20210613_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='support_artists',
            field=models.ManyToManyField(blank=True, related_name='gigs', to='artists.Artist'),
        ),
    ]
