# Generated by Django 3.2.4 on 2021-06-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_alter_gig_headliner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='support_artists',
            new_name='artists',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='headliner',
        ),
    ]
