# Generated by Django 3.2.4 on 2021-06-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20210611_1237'),
        ('gigs', '0006_auto_20210613_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='artists',
            new_name='support_artists',
        ),
        migrations.AddField(
            model_name='gig',
            name='headliner',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='gig_headliner', to='artists.artist'),
            preserve_default=False,
        ),
    ]
