# Generated by Django 3.2.4 on 2021-06-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_auto_20210614_0922'),
        ('gigs', '0007_auto_20210613_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='headliner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_headliner', to='artists.artist'),
        ),
    ]
