# Generated by Django 3.2.4 on 2021-07-26 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='artists.Genre'),
        ),
        migrations.AddField(
            model_name='track',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='artists.Link'),
        ),
        migrations.AddField(
            model_name='track',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='release',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='artists.Release'),
        ),
        migrations.AddField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='release',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='release',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='releases', to='artists.Genre'),
        ),
        migrations.AddField(
            model_name='release',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='releases', to='artists.Link'),
        ),
        migrations.AddField(
            model_name='release',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musician',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='musicians', to='artists.Instrument'),
        ),
        migrations.AddField(
            model_name='musician',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musician', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_genres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artists.Genre'),
        ),
        migrations.AddField(
            model_name='artist',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artists.Link'),
        ),
        migrations.AddField(
            model_name='artist',
            name='musicians',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artists.Musician'),
        ),
        migrations.AddField(
            model_name='artist',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
