# Generated by Django 3.2.4 on 2021-06-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='credits',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='artists.Musician'),
        ),
    ]
