# Generated by Django 3.2.4 on 2021-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_track_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='credits',
        ),
    ]
