# Generated by Django 3.2.4 on 2021-06-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_remove_track_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='artists',
        ),
        migrations.AddField(
            model_name='artist',
            name='musicians',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artists.Musician'),
        ),
    ]
