# Generated by Django 3.2.4 on 2021-06-11 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0004_auto_20210610_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_genres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musician',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musician', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='release',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
