# Generated by Django 3.2.4 on 2021-06-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20210611_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='release',
        ),
        migrations.AddField(
            model_name='track',
            name='release',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='artists.Release'),
        ),
    ]
