# Generated by Django 3.2.4 on 2021-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_auto_20210614_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
